### ISSUE TITLE
genererate embed code?

### ISSUE THREAD

**Issue by jflawren** [aug-riedinger/google-docs-publisher#1]
```
Is there a way to generate code to embed that reformated gdoc code in a wordpress post (or elsewhere)? thanks so much for your this code!! josh
```

**Comment by aug-riedinger** [comment]
Hi @jflawren 

Here's how you can do this:

You need to install the iframe plugin: https://fr.wordpress.org/plugins/iframe/
Then insert in your post the following:
```
[iframe src="http://gdoc.pub/<the hash of your file>/raw" width="100%" height="500"]
```

Eg of URL: http://gdoc.pub/1OO-pC727TFEw0ffgp-l0ingL19bD-adI7Nr0BykFje8/raw (not the `/raw` that is important here)

The height of the document cannot be auto-calculated this way. I suggest you set `height="xxx"` according to your document size. If you need this to be dynamic (eg. the file is subject to changes), please come back here and we'll find a neat way to adapt the height (using the same trick as the http://gdoc.pub one).

Good luck!

**Comment by aug-riedinger** [comment]
Let me know if you have trouble doing this. Closing for now.

**Comment by yellowjaguar5** [comment]
Hello!
Sorry to reopen an old issue, but I would like to know how to add a dynamic height to an embedded document.
Thanks!

**Comment by aug-riedinger** [comment]
You'll have to add some javascript  to your document. If this helps, here's how I do it in my own page:

```
        iframe.addEventListener('load', function(e){
          document.title = iframe.contentWindow.document.title;
          setTimeout(function(){
            var height = iframe.contentWindow.document.body.offsetHeight+50;
            document.getElementsByClassName('iframe-wrapper')[0].setAttribute('style', 'height: '+height+'px;');
            if (window.location.hash && window.location.hash[0] === '#') {
              scrollTo(document.body, iframe.contentWindow.document.getElementById(window.location.hash.replace(/^#/, '')).offsetTop, 250);
            }
          }, 1000);
        });
```

**Comment by yellowjaguar5** [comment]
Neat. Thanks!
