### ISSUE TITLE
doc wont publish and returns Cannot GET error

### ISSUE THREAD

**Issue by N3llz** [aug-riedinger/google-docs-publisher#10]
When I try to publish my doc, it opens up a webpage with plain text saying `Cannot GET` followed by my doc's url. It won't publish at all so far, and I've tried with a few documents without any success.

**Comment by aug-riedinger** [comment]
Please send me your document url otherwise I can't help !

**Comment by N3llz** [comment]
Here is a [test doc](https://docs.google.com/document/d/e/2PACX-1vS3KK2tlJyHWihurB2VvyDR8CBU2c_t-hooH9RVLHIZN22RXgAtRuoQmq1EOjcpC_o-zSCvPg1wmDCH/pub) that returns the same error. Note that if you click that link, it will publish, but what doesn't work is when I enter that url into [https://gdoc.pub/](https://gdoc.pub/)

**Comment by aug-riedinger** [comment]
Indeed, Google changed its URL format...

Now fixed: https://gdoc.pub/e/2PACX-1vS3KK2tlJyHWihurB2VvyDR8CBU2c_t-hooH9RVLHIZN22RXgAtRuoQmq1EOjcpC_o-zSCvPg1wmDCH

Have fun using gdoc.pub!
