### ISSUE TITLE
gdocs.pub has been flagged as malicious by mcafee

### ISSUE THREAD

**Issue by softwario** [aug-riedinger/google-docs-publisher#14]
Not a code issue but wanted to make sure you were aware.  When a user tries to access https://gdocs.pub they're alerted that this is a known malicious site and warned to stay away.  You can check their database here:
https://www.trustedsource.org/en/feedback/url

and see that it's listed as a phishing site.

**Comment by aug-riedinger** [comment]
Thanks for providing this feedback. This is not a good news :disappointed: but it is not the first time...

I have been reaching them, we'll see how it goes.

**Comment by aug-riedinger** [comment]
Yai!
They have been verifying it and I got un-blacklisted:

![image](https://cloud.githubusercontent.com/assets/1970156/24851645/bc55113e-1dd4-11e7-9496-bdc97069667c.png)

Thanks for reporting, I would have never been aware of this!
