### ISSUE TITLE
Hyperlinks in table of contents

### ISSUE THREAD

**Issue by pvnkmrksk** [aug-riedinger/google-docs-publisher#16]
The hyperlinks work in the original published version but nothing happens when using this. Is it a bug or a missing feature.

https://gdoc.pub/doc/1q-vsEFExos8Oj_eDzrHcQZGZ2ld-k8Yp8Y4UlyZdrY0#?usp=sharing

**Comment by aug-riedinger** [comment]
Hi,

Would you mind explaining what is going wrong in detail?

When I click the table of content link, my browser scrolls down to the section. Not yours? What browser are you using?

**Comment by aug-riedinger** [comment]
Closing for now. Please reopen if something is missing.
