### ISSUE TITLE
Issue with sharing published google document

### ISSUE THREAD

**Issue by redgredg** [aug-riedinger/google-docs-publisher#17]
Hello everyone!

Hope all is doing great!

We just used this website to publish a Google Document since it doesn't change any formatting and we really like it.

However we have an issue with sharing the link using Beacons. Whenever we share the published link using a Beacon the <title/> shows up.

Is there a way to have that removed? 

You can see a sample screenshot at https://www.screencast.com/t/99q7dUPY

Any response will be appreciated.

**Comment by aug-riedinger** [comment]
Fixed as of today!

Have fun using gdoc.pub
