### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by mu3** [aug-riedinger/google-docs-publisher#3]
![screen shot 2016-04-28 at 20 17 30](https://cloud.githubusercontent.com/assets/661220/14895089/94483e34-0d7f-11e6-8b8f-39dd7ddc27d8.png)

Not sure but looks like CloudFlare breaks the encoding.
Text is totally ok, I tried to play with it but the � artifacts are always here. In new locations if some changes were made.

Here's a doc:
https://docs.google.com/document/d/1LLGEgvj2fJrENXkGKDat8dBMRyew5phLsFY0FsKqcOY/pub
http://gdoc.pub/1LLGEgvj2fJrENXkGKDat8dBMRyew5phLsFY0FsKqcOY

The bug is present in all browsers.
Also note the text contains hebrew characters.

**Comment by aug-riedinger** [comment]
Thanks for reporting. I fixed the issue, should be better now!
