### ISSUE TITLE
"Not Found"

### ISSUE THREAD

**Issue by junctioncitypress** [aug-riedinger/google-docs-publisher#34]
Hi Augustin, I'm a huge fan of Google Docs Publisher. Been using it to format the following spreadsheet for 9 months now without issue, but today it stopped working. It just says "Not Found."

Here is the google doc:

https://docs.google.com/spreadsheets/d/e/2PACX-1vQTl0UIfDriIOEJUXjVCPOSSB5yKe0nI4aLmeTglMKGdwaWQUidl4zCGB43DEy5yMKYOPo76mHRFN7t/pubhtml?gid=1172294093&single=true

Please let me know if there's anything to be done, thank you!!

**Comment by augnustin** [comment]
Hello @junctioncitypress 

I just made a change that broke spreadsheets.

It is fixed now: https://gdoc.pub/sheet/e/2PACX-1vQTl0UIfDriIOEJUXjVCPOSSB5yKe0nI4aLmeTglMKGdwaWQUidl4zCGB43DEy5yMKYOPo76mHRFN7t#html?gid=1172294093&single=true

Have fun using gdoc.pub

best
