### ISSUE TITLE
Text Is Cut Off and Formatting Is Not Preserved

### ISSUE THREAD

**Issue by wpazzurri** [aug-riedinger/google-docs-publisher#35]
Hello! Unfortunately the text is cut off and the formatting is not preserved. See images of how it looks in the editing window vs published with your service. Is there a way to fix this? If so, I'd love to learn how. If not, I would like to un-publish this so it cannot be found in this state. Thank you!

![Screen Shot 2019-06-20 at 7 11 19 PM](https://user-images.githubusercontent.com/52054655/59886944-3dec1800-938f-11e9-9e42-1912e4ebac43.png)

![Screen Shot 2019-06-20 at 7 10 49 PM](https://user-images.githubusercontent.com/52054655/59886945-3dec1800-938f-11e9-8c17-617a266a48b7.png)

**Comment by augnustin** [comment]
Hi @wpazzurri 

You need to be aware that the only thing gdoc.pub does is surrounding the published document to make it look paper size. So regarding your display issue, you need to look at the *published version of the google doc* (the URL you copy/pasted in gdoc.pub): if it has a display issue, then there is nothing I can do for you. The only suggestion I can make is that you reformat your original document to have it look the way you want.

Concerning the un-publish, in the same way, I don't have any control on this. What you need to do is to un-publish it on the google docs platform, the same way you published it and then click on some button like "Stop publishing". If it is not there, it won't be in gdoc.pub (5 min later). That said, you should not worry too much about people finding your document: without the URL, there are no chances it can be found anywhere.

Good luck
