### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by Basil1105** [aug-riedinger/google-docs-publisher#38]
I started and added my first google doc and it worked.
I added this one and it does not show. What am I doing wrong?
https://gdoc.pub/doc/1lbZEUikAlrGYcPHJBYIj7nwAGIbyvtpMKA2hZIJNH64#heading=h.do76ppl3thdt

**Comment by Basil1105** [comment]
Sorry!!
I figured out what I did wrong.
I need to publish before I can convert.
Problem solved.
User Error [Embarrassed]

**Comment by augnustin** [comment]
All good! Have fun using gdoc.pub
