### ISSUE TITLE
Accessing published docs secured (HTTPS)

### ISSUE THREAD

**Issue by ShayFB** [aug-riedinger/google-docs-publisher#4]
I need to access the URL with https.
Until recent, the generated link (HTTP://gdoc...) was accessible also by HTTPs.
Now it sometimes works and sometimes doesn't

Please assist,
Thanks

**Comment by aug-riedinger** [comment]
Here you go: https://gdoc.pub/1OO-pC727TFEw0ffgp-l0ingL19bD-adI7Nr0BykFje8

Made the app 100% https, since I shall add authentication at some point.

Best

**Comment by ShayFB** [comment]
Thank you very much!
