### ISSUE TITLE
Not seeing my content 

### ISSUE THREAD

**Issue by akayezee** [aug-riedinger/google-docs-publisher#40]
When I paste my public doc url, all I see is "Found" at the top left corner and none of my content. This looks pretty simple to use, but I can't get it to work. Could someone please help me out :)

**Comment by augnustin** [comment]
Hello @akayezee 
I need you to send me the URL of the document. If you don't want it to be public, [write me an email](https://augustin-riedinger.fr/fr/contact/).
Best

**Comment by akayezee** [comment]
Hi Augnustin, 

I am pretty sure the docs were public. Nonetheless, I am no longer going to use google docs for my project, so I no longer need help with this :) 
Thank you for your time!
