### ISSUE TITLE
Text appearing in header: Automatisch alle 5 Minuten aktualisiert

### ISSUE THREAD

**Issue by MarketingMandy** [aug-riedinger/google-docs-publisher#42]
Hello

This text is now appearing in the header of published documents, which has never appeared before. I'm sure it means the page is automatically updated every 5 minutes, but it'd be helpful to be in the source language if it is there! Any chance it can be removed or reflect the language of the document?

**Comment by augnustin** [comment]
It should not be there. Do you have a document example so I can investigate on this?

**Comment by MarketingMandy** [comment]
Thanks: here is an example document we have posted: https://gdoc.pub/doc/e/2PACX-1vTfWbQ0FG1dwLoMzD2j7HWkfJpSeHRlohrWHevtKAALffNpSDfTBi7FV9j4jyms8vFC2UApIXz2C0r-

**Comment by augnustin** [comment]
Hello,

Thanks for reporting. In fact, the change did come from a google change.

I edited my processing to fix that along other margin issues.

Best

**Comment by MarketingMandy** [comment]
Thanks so much for your quick and effective response!

All the best
Mandy
