### ISSUE TITLE
Image not wrapping 

### ISSUE THREAD

**Issue by AsawariMathur** [aug-riedinger/google-docs-publisher#44]
I was facing this issue with google docs and now with gdoc.pub too. In my document, the images are not wrapping in the text to look neat and formated.

https://gdoc.pub/doc/e/2PACX-1vT6t3uSOHARVubyXGe6pkJbExlNVbk2pfBpuITK6evOsQRH_aaZQoKp7iL0tYrDDyHvG_o6xMFQCNrG

**Comment by augnustin** [comment]
Hello,

Apologies for that but if it is not there in the original google doc published document, it won't be there with gdoc.pub.

Best
