### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by Pawtiko** [aug-riedinger/google-docs-publisher#5]

**Comment by aug-riedinger** [comment]
I'm working on it and plan to be back very shortly.

To give a little more explanations, someone used gdoc.pub to host a phishing google docs (fake message from whatever bank or account that asks for your details) and it needs to be blocked. 

It is a pity that something useful becomes abused by stupid pirates but that's how internet works. :(

**Comment by Pawtiko** [comment]
I understand - and thanks for putting it back up again!
