### ISSUE TITLE
gdoc.pub File Doesn't Seem to Work

### ISSUE THREAD

**Issue by kacicohn** [aug-riedinger/google-docs-publisher#53]
When I paste my gdoc.pub URL into the address bar, it seems to just re-direct back to the original version of the published Google doc 🤔

gdoc.pub URL: https://gdoc.pub/doc/12XVF5calNt_94rCgqRGzt4bLInP_4AXxXqVX6wZBLv0
Original published URL: https://docs.google.com/document/d/12XVF5calNt_94rCgqRGzt4bLInP_4AXxXqVX6wZBLv0/pub

Any help would be appreciated!

**Comment by augnustin** [comment]
@kacicohn This is a security feature because gdoc.pub happens to be used by people who write illegitimate documents.

Please write me there: https://augustin-riedinger.fr/contact so I can tell you how to remove this restriction.

Cheers

**Comment by vonguyenkhang** [comment]
> @kacicohn This is a security feature because gdoc.pub happens to be used by people who write illegitimate documents.
> 
> Please write me there: https://augustin-riedinger.fr/contact so I can tell you how to remove this restriction.
> 
> Cheers

hi, when I press submit on that contact form, there's an error "An error occured, please try later". Happend on both Edge and Chrome.
![image](https://github.com/augnustin/google-docs-publisher/assets/15910168/c8d9a2fd-41a1-49fb-b9b1-dea465165ec8)

**Comment by johndove** [comment]
Didn't work, again.
Went to the link and for the same error.
Thanks for your help,
Blessings,
John
