### ISSUE TITLE
Header row in google sheet with 90 degrees rotated text isn't rendered as is

### ISSUE THREAD

**Issue by amar-sanakal** [aug-riedinger/google-docs-publisher#55]
https://gdoc.pub/sheet/e/2PACX-1vRzmtHtYbqtmV5WagNV_zUODYmUS4yFCMKNsSOW2vV6qSAfvBOnrP6Wwr6HmbfFL_9thvUlYtEQf1n2#html?gid=0 - in my sheet, the header row entries are rotated 90 degrees and displayed vertically. While searching for a better way to render the page, I found your project. Is it possible to "fix" this?

**Comment by augnustin** [comment]
The rule of thumb in gdoc.pub is : 

> If it's not in the google published version, it won't be there in the gdoc.pub one.

I'm afraid there is nothing I can do here.

Best
