### ISSUE TITLE
Font and Banner changed suddenly without any changes to the original doc

### ISSUE THREAD

**Issue by bazgrimtv** [aug-riedinger/google-docs-publisher#57]
I have three docs published using google doc publisher and so far it has been great. But as of yesterday, I noticed that the formatting for all 3 docs is incorrect. It now displays with a font different from what is actually in the original google doc (should be Asul, but now looks like Times New Roman) and the ugly banner at the top that has the title and "Automatically updates every 5 minutes" now appears. Just a couple days ago it showed the correct font without the banner at the top. I haven't made any changes to the original doc since then, so I'm wondering what happened? Thanks in advance for any help.

**Comment by augnustin** [comment]
Thanks for reporting, this is fixed. Reopen otherwise. Cheers
