### ISSUE TITLE
Text at the top in German?

### ISSUE THREAD

**Issue by Demthios** [aug-riedinger/google-docs-publisher#58]
The text at the very top on our page is in German, translated it is "Automatically updated every 5 minutes " but the document is in English how can we correct this to at least display in English?  Thanks!

**Comment by augnustin** [comment]
Hi,
This sentence shouldn't be displayed, I'll have it removed ASAP.

**Comment by augnustin** [comment]
This is fixed. Sorry for little delay. :baby_bottle:
