### ISSUE TITLE
Double Scrollbars when navigating to another gdoc.pub version of a doc from a link in another

### ISSUE THREAD

**Issue by qhoffman** [aug-riedinger/google-docs-publisher#8]
If you have a page with a link to another published doc, the page is not aware of the change and does not  resize the containing document appropriately.  

So if the second doc you navigate to is larger than the first one, you get a scrollbar inside the iframe (I haven't had a chance to look a the source... I assume it is using a iframes), as well as the scrollbar for the master document that you had from the first doc you loaded.
## Example

![capture2](https://cloud.githubusercontent.com/assets/7084651/19609538/c6f1efaa-97a5-11e6-8e20-b5d70fd54d8b.JPG)

**Comment by aug-riedinger** [comment]
Hi,
I must have missed your issue.
Can you send me an example so I can have a look at this?

**Comment by aug-riedinger** [comment]
Should be fixed now. Closing.
