### ISSUE TITLE
'Not found'

### ISSUE THREAD

**Issue by dotherightthing** [aug-riedinger/google-docs-publisher#9]
After pasting my URL into the "Publish your doc right now" field, the copied link results in 'Not found'.

The URL is https://docs.google.com/document/d/1Z1atNALhSxbwLVdop0URfsyG74Bqp8X8J0dx5fM5OkY/pub

Thanks,
Dan

**Comment by aug-riedinger** [comment]
Better now:
https://gdoc.pub/1Z1atNALhSxbwLVdop0URfsyG74Bqp8X8J0dx5fM5OkY

This happened because your document contained URLs which have been suspected to be phishing ones. Obviously they weren't, so I took the chance to improve my detection algorithm.

Have fun using gdoc.pub!

**Comment by dotherightthing** [comment]
Thanks, it is working now. Is the layout as you would expect? To my eye the published document still looks very different to the original:

![screen shot 2016-11-17 at 2 18 11 pm](https://cloud.githubusercontent.com/assets/638871/20372567/0d53ece2-acd1-11e6-89c5-0d687e23f047.png)

**Comment by aug-riedinger** [comment]
Not much besides the line height. I increased it slightly more, tell me what you think.

Best.
